# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Branch Workflow

on:
  push:
    branches-ignore: [main]

jobs:
  BUILD:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Maven Package
        run: mvn -B clean package -DskipTests
      - name: Unit Test
        run: mvn clean test -P unit-test
